<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '8e7e8d17967b3faadc089e6cb04735f0',
  'MAILER_DSN' => 'smtp://localhost:1025',
  'DATABASE_URL' => 'mysql://root@localhost:3306/bddaja?serverVersion=5.7',
);
